apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: dotnet-basic-qrbjonyq
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jsmid/dotnet-basic-qrbjonyq:22f40c66fa0f03c481e4fbadafbbf214972a6e57@sha256:860717c5c34e1b2b0fd6f990ecc66801a24ba8efee9188802a51ded8d54ef305
        name: container-image  
