apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dotnet-basic-qrbjonyq
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/dotnet-basic-qrbjonyq:4a8828197ff4479d06d2c53aaea8038efdc03c7c@sha256:0b503155f68ed9f5798bf09d8be6ac893ae8c28c35e01749b1be99012490b9e6
          name: container-image
